server:
  port: 8092
spring:
  config:
    activate:
      on-profile: prod

openapi:
  service:
    api-docs: api-service
    server: http://localhost:{server.port}
    title: API Service
    version: 1.0.0
