server:
  port: 8091
spring:
  config:
    activate:
      on-profile: test

openapi:
  service:
    api-docs: api-service
    server: http://localhost:{server.port}
    title: API Service
    version: 1.0.0
